"""Emit the fine-tuning grid as a queue file: parents x {full, lora r4/16/64} x {code, sup}."""
from __future__ import annotations

import argparse
from pathlib import Path

from rankfile.config import load_yaml


def grid_lines(
    parents: list[str],
    ranks: list[int],
    tasks: list[str],
    lrs: dict[tuple[str, str], float | dict[int, float]],
    py: str,
) -> list[str]:
    """A LoRA entry in `lrs` is one LR for every rank or a {rank: lr} map."""

    def lora_lr(task: str, r: int) -> float:
        v = lrs[("lora", task)]
        return v[r] if isinstance(v, dict) else v

    lines = []
    for parent in parents:
        pname = Path(parent).name
        for task in tasks:
            lines.append(
                f"{py} -m rankfile.finetune --parent {parent} --method full --task {task} "
                f"--lr {lrs[('full', task)]} --name {pname}__full_{task}"
            )
            for r in ranks:
                lines.append(
                    f"{py} -m rankfile.finetune --parent {parent} --method lora --task {task} "
                    f"--rank {r} --lr {lora_lr(task, r)} --name {pname}__lora{r}_{task}"
                )
    return lines


def _lora_lrs(task: str) -> float | dict[int, float]:
    # lora_{task}.yaml was used by the first grid and is immutable (CLAUDE.md §8 rule 3);
    # per-rank LRs from the rank sweep live in a separate file that takes precedence.
    by_rank = Path(f"configs/finetune/lora_{task}_by_rank.yaml")
    if by_rank.exists():
        return {int(r): float(lr) for r, lr in load_yaml(by_rank)["lr_by_rank"].items()}
    return load_yaml(f"configs/finetune/lora_{task}.yaml")["lr"]


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--parents", nargs="+", required=True)
    ap.add_argument("--out", required=True)
    ap.add_argument("--ranks", nargs="+", type=int, default=[4, 16, 64])
    ap.add_argument("--tasks", nargs="+", default=["code", "sup"])
    a = ap.parse_args()
    lrs = {
        ("full", "code"): load_yaml("configs/finetune/full_code.yaml")["lr"],
        ("full", "sup"): load_yaml("configs/finetune/full_sup.yaml")["lr"],
        ("lora", "code"): _lora_lrs("code"),
        ("lora", "sup"): _lora_lrs("sup"),
    }
    lines = grid_lines(a.parents, a.ranks, a.tasks, lrs, ".venv\\Scripts\\python.exe")
    Path(a.out).write_text(
        "# generated by scripts/ft_grid.py\n" + "\n".join(lines) + "\n",
        encoding="utf-8",
    )
    print(f"wrote {len(lines)} lines to {a.out}")


if __name__ == "__main__":
    main()
