"""Emit the fine-tuning grid as a queue file: parents x {full, lora r4/16/64} x {code, sup}."""
from __future__ import annotations

import argparse
from pathlib import Path

from rankfile.config import load_yaml


def grid_lines(
    parents: list[str],
    ranks: list[int],
    tasks: list[str],
    full_lr: float,
    lora_lr: float,
    py: str,
) -> list[str]:
    lines = []
    for parent in parents:
        pname = Path(parent).name
        for task in tasks:
            lines.append(
                f"{py} -m rankfile.finetune --parent {parent} --method full --task {task} --lr {full_lr} --name {pname}__full_{task}"
            )
            for r in ranks:
                lines.append(
                    f"{py} -m rankfile.finetune --parent {parent} --method lora --task {task} --rank {r} --lr {lora_lr} --name {pname}__lora{r}_{task}"
                )
    return lines


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--parents", nargs="+", required=True)
    ap.add_argument("--out", required=True)
    ap.add_argument("--ranks", nargs="+", type=int, default=[4, 16, 64])
    ap.add_argument("--tasks", nargs="+", default=["code", "sup"])
    a = ap.parse_args()
    full_lr = load_yaml("configs/finetune/full.yaml")["lr"]
    lora_lr = load_yaml("configs/finetune/lora.yaml")["lr"]
    lines = grid_lines(a.parents, a.ranks, a.tasks, full_lr, lora_lr, ".venv\\Scripts\\python.exe")
    Path(a.out).write_text(
        "# generated by scripts/ft_grid.py\n" + "\n".join(lines) + "\n",
        encoding="utf-8",
    )
    print(f"wrote {len(lines)} lines to {a.out}")


if __name__ == "__main__":
    main()
