"""Emit the fine-tuning grid as a queue file: parents x {full, lora r4/16/64} x {code, sup}."""
from __future__ import annotations

import argparse
from pathlib import Path

from rankfile.config import load_yaml


def grid_lines(
    parents: list[str],
    ranks: list[int],
    tasks: list[str],
    lrs: dict[tuple[str, str], float],
    py: str,
) -> list[str]:
    lines = []
    for parent in parents:
        pname = Path(parent).name
        for task in tasks:
            lines.append(
                f"{py} -m rankfile.finetune --parent {parent} --method full --task {task} "
                f"--lr {lrs[('full', task)]} --name {pname}__full_{task}"
            )
            for r in ranks:
                lines.append(
                    f"{py} -m rankfile.finetune --parent {parent} --method lora --task {task} "
                    f"--rank {r} --lr {lrs[('lora', task)]} --name {pname}__lora{r}_{task}"
                )
    return lines


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--parents", nargs="+", required=True)
    ap.add_argument("--out", required=True)
    ap.add_argument("--ranks", nargs="+", type=int, default=[4, 16, 64])
    ap.add_argument("--tasks", nargs="+", default=["code", "sup"])
    a = ap.parse_args()
    lrs = {
        ("full", "code"): load_yaml("configs/finetune/full_code.yaml")["lr"],
        ("full", "sup"): load_yaml("configs/finetune/full_sup.yaml")["lr"],
        ("lora", "code"): load_yaml("configs/finetune/lora_code.yaml")["lr"],
        ("lora", "sup"): load_yaml("configs/finetune/lora_sup.yaml")["lr"],
    }
    lines = grid_lines(a.parents, a.ranks, a.tasks, lrs, ".venv\\Scripts\\python.exe")
    Path(a.out).write_text(
        "# generated by scripts/ft_grid.py\n" + "\n".join(lines) + "\n",
        encoding="utf-8",
    )
    print(f"wrote {len(lines)} lines to {a.out}")


if __name__ == "__main__":
    main()
